### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [WheteThunger/DebugMissingParentEntity#1]
upon installing the cs file it doesnt let me install it i this error message
Error while compiling: DebugMissingParentEntity.cs(36,59): error CS1061: Type `uint' does not contain a definition for `Value' and no extension method `Value' of type `uint' could be found. Are you missing `Newtonsoft.Json.Linq' using directive?  
any help?

**Comment by WheteThunger** [comment]
The version you have installed is for the force wipe tomorrow. Look at the history of the file and use a previous version of it.

**Comment by ghost** [comment]
ok thank you sure thats why it was not working for me lol
how would i go back and grab the last version? im new to this site

**Comment by WheteThunger** [comment]
There are a few ways to get to it, but here is the link.
https://raw.githubusercontent.com/WheteThunger/DebugMissingParentEntity/989134b3db177c3d8d010c4145d3ecc2cb61d493/DebugMissingParentEntity.cs

**Comment by ghost** [comment]
thank u so much man sorry to be a pain if i was

**Comment by ghost** [comment]
i click the link but i can download it

**Comment by WheteThunger** [comment]
Right click and save as

**Comment by ghost** [comment]
roger ok now i know for future
